### ISSUE TITLE
problem with TE and bitcoin

### ISSUE THREAD

**Issue by MadRatSRP** [bonii-xx/MinecraftBitcoin#3]
java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class cofh.core.inventory.ComparableItemStack id= 252525823 hashCode= -469978147 toString= cofh.core.inventory.ComparableItemStack@252525823{m:70, i:cofh.thermalfoundation.item.ItemCoin@1534025102, v:5160}; object #2 =class cofh.core.inventory.ComparableItemStack id= 252525823 hashCode= -469978147 toString= cofh.core.inventory.ComparableItemStack@252525823{m:70, i:cofh.thermalfoundation.item.ItemCoin@1534025102, v:5160}

    at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
    at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:426)
    at gnu.trove.map.hash.TObjectIntHashMap.rehash(TObjectIntHashMap.java:191)
    at gnu.trove.impl.hash.THash.compact(THash.java:201)
    at gnu.trove.impl.hash.THash.removeAt(THash.java:272)
    at gnu.trove.impl.hash.TObjectHash.removeAt(TObjectHash.java:104)
    at gnu.trove.map.hash.TObjectIntHashMap.removeAt(TObjectIntHashMap.java:292)
    at gnu.trove.map.hash.TObjectIntHashMap.remove(TObjectIntHashMap.java:277)
    at cofh.thermalexpansion.util.managers.dynamo.NumismaticManager.removeFuel(NumismaticManager.java:86)
    at boni.bitcoin.ThermalExpansion.removeBitcoinRecipe(ThermalExpansion.java:22)
    at boni.bitcoin.ThermalExpansion.updateBitcoinRecipe(ThermalExpansion.java:26)
    at boni.bitcoin.stockexchange.BullAndBear.setCurrentValue(BullAndBear.java:90)
    at boni.bitcoin.stockexchange.BullAndBear.updateCurrentValue(BullAndBear.java:138)
    at boni.bitcoin.stockexchange.BullAndBear.modifyValue(BullAndBear.java:99)
    at boni.bitcoin.stockexchange.BullAndBear.onWorldTick(BullAndBear.java:80)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2737_BullAndBear_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:776)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

**Comment by MadRatSRP** [comment]
Here is what COFH team responded to me:
"I think CoFH switched from Trove to FastUtils after Forge did. I don't know if that's actually the cause of the problem here, but it looks pretty likely that the bitcoin mod is at fault. Probably an API change they need to adapt to."

**Comment by bonii-xx** [comment]
Post the full crashlog somewhere

**Comment by MadRatSRP** [comment]
https://paste.dimdev.org/ijeqibapaw.mccrash

**Comment by bonii-xx** [comment]
Hm, this is really weird. Bitcoin doesn't do anything with the stuff directly, it just uses COFHs API. The error still shows it uses the trove utils, not the fastutils so you're either out of date or they haven't released a new version with the fastutils yet. Anyway, that can't be it since it used to work before. It looks like *after* the old recipe was removed, the trove map complains about having invalid entries. It might be some other mod added a recipe causing this. It might be that a newer version using fastutils indirectly fixes it though.

I'd say check if it also happens with only TE and bitcoin and update COFH mods to the highest possible version.

**Comment by MadRatSRP** [comment]
Well, maybe you should ask COFH team for help?

**Comment by MadRatSRP** [comment]
Hi, its happening again :D
[crash-2020-03-31_15.24.19-server.txt](https://github.com/bonii-xx/MinecraftBitcoin/files/4416728/crash-2020-03-31_15.24.19-server.txt)
